---
version: "2"
linters:
  default: all
  disable:
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - ireturn
    - maintidx
    - mnd
    - tagliatelle
    - wsl
  enable:
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
          deny:
            - pkg: io/ioutil
              desc: 'replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil'
    revive:
      rules:
        - name: var-naming
          disabled: true
    varnamelen:
      min-name-length: 2
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    goimports:
      local-prefixes:
        - github.com/E4-Computer-Engineering/xiraid-exporter
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
