{
 "title": "Xiraid RAID Overview New",
 "tags": [ "xiraid" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(xiraid_raid_info,job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(xiraid_raid_info{job=\"$job\"},nodename)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(xiraid_raid_info{job=\"$job\",nodename=~\"$nodename\"}, instance)"
    }
   },
   {
    "name": "raid_name",
    "label": "RAID Name",
    "query": {
     "query": "label_values(xiraid_raid_info{job=\"$job\",nodename=~\"$nodename\",instance=~\"$instance\"}, raid_name)"
    }
   },
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(xiraid_raid_device_state{raid_name=~\"$raid_name\"},device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "License Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xiraid_license_valid{instance=~\"$instance\"}",
     "legendFormat": "License Status"
    }
   ]
  },
  {
   "title": "RAID State",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "xiraid_raid_state{instance=~\"$instance\", raid_name=~\"$raid_name\"}",
     "legendFormat": "{{raid_name}} - {{state}}"
    }
   ]
  },
  {
   "title": "RAID Active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xiraid_raid_active{instance=~\"$instance\", raid_name=~\"$raid_name\"}",
     "legendFormat": "{{raid_name}}"
    }
   ]
  },
  {
   "title": "License Disk Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xiraid_license_disks_in_use{instance=~\"$instance\"}",
     "legendFormat": "In Use"
    },
    {
     "expr": "xiraid_license_disks_total{instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAID Configured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xiraid_raid_config{instance=~\"$instance\", raid_name=~\"$raid_name\"}",
     "legendFormat": "{{raid_name}}"
    }
   ]
  },
  {
   "title": "Collectors scrape error",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xiraid_scrape_error{instance=~\"$instance\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "RAID Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAID Arrays Overview",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "xiraid_raid_info{instance=~\"$instance\", raid_name=~\"$raid_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RAID Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "xiraid_raid_size_bytes{instance=~\"$instance\", raid_name=~\"$raid_name\"}",
       "legendFormat": "{{raid_name}}"
      }
     ]
    },
    {
     "title": "Device State",
     "type": "stat",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "xiraid_raid_device_state{instance=~\"$instance\", raid_name=~\"$raid_name\", device=~\"$device\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Device Faulty Sectors ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 18 },
     "targets": [
      {
       "expr": "xiraid_drive_faulty_sectors_total{instance=~\"$instance\", raid_name=~\"$raid_name\", device=~\"$device\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "RAID Meory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "xiraid_raid_memory_usage_bytes{instance=~\"$instance\", raid_name=~\"$raid_name\"}",
       "legendFormat": "{{raid_name}}"
      }
     ]
    }
   ]
  }
 ]
}